### ISSUE TITLE
downsample method

### ISSUE THREAD

**Issue by zhwzhong** [Sunbaoli/PMBANet_DSR#1]
Hello Xinchen,
          Thanks for your great work!
           When I was run your code, I meet some questions and I wish that you could help me. The first question is can you show me your code about how to produce your low-resolution depth map, I have tried Matlab(imresize  function) and Python (Pytroch, interpolate), but I can't get the same result as your provided in your data folder. The second question is the pixel value range that you used to calculate MAD, is 0-1 or 0-255? I use your code with your checkpoint, but I can't get the correct result as your paper has provided. Thanks.

**Comment by Sunbaoli** [comment]
Thank you for your interest in our work. We produced LR depth maps by 'cv2.resize(img, size, interpolation=cv2.INTER_CUBIC)'. The pixel value range is 0-255.&nbsp;



If you have any questions at running this code, you can email me.



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Sunbaoli/PMBANet_DSR"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月31日(星期五) 晚上9:20
收件人:&nbsp;"Sunbaoli/PMBANet_DSR"<PMBANet_DSR@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[Sunbaoli/PMBANet_DSR] downsample method (#1)





 
Hello Xinchen,
 Thanks for your great work!
 When I was run your code, I meet some questions and I wish that you could help me. The first question is can you show me your code about how to produce your low-resolution depth map, I have tried Matlab(imresize  function) and Python (Pytroch, interpolate), but I can't get the same result as your provided in your data folder. The second question is the pixel value range that you used to calculate MAD, is 0-1 or 0-255? I use your code with your checkpoint, but I can't get the correct result as your paper has provided. Thanks.

**Comment by zhwzhong** [comment]
Thanks for your generous help.  At last, can you tell me the way you add gaussian noise to the depth data,  does it need clip the pixel range to [0, 1] before sending it to the network for inference?

**Comment by Sunbaoli** [comment]
As expounded in Sec 5-B，we added add Gaussian noise with a variance of 25 to the original Middlebury datasets, and then downsample the polluted datasets at four scales. We use 'ToTensor'(data.py) to process depth map before sending it to the network.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Sunbaoli/PMBANet_DSR"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月1日(星期六) 凌晨1:23
收件人:&nbsp;"Sunbaoli/PMBANet_DSR"<PMBANet_DSR@noreply.github.com&gt;;
抄送:&nbsp;"Gentleman"<1115395284@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [Sunbaoli/PMBANet_DSR] downsample method (#1)





 
Thanks for your generous help.  At last, can you tell me the way you add gaussian noise to the depth data,  does it need clip the pixel range to [0, 1] before sending it to the network for inference?
